<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula
[
<!ELEMENT pelicula (titulo,estreno,director,reparto)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT estreno (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT reparto (#PCDATA)>
]>

<pelicula>
    <titulo></titulo>
    <estreno></estreno>
    <director></director>
    <reparto></reparto>
</pelicula>