=== EmmanuelRamosBiado/Primero-de-Daw/LENGUAJE DE MARCAS/UT6_DTD/Prácticas/Práctica DTD/Ejercicio_02.dtd
<!ELEMENT afiliados (afiliado+)>
<!ELEMENT afiliado (dni_nie,nombre,apellidos,situacion,nacimiento,bajas,prestaciones)>
<!ELEMENT dni_nie (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT situacion (#PCDATA)>
<!ATTLIST situacion situacion (en_paro|en_activo|jubilado|edad_no_labora) #REQUIRED>
<!ELEMENT nacimiento (dia,mes,anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT bajas (baja*)>
<!ELEMENT baja (causa,b_inicio,b_final?)>
<!ELEMENT causa (#PCDATA)>
<!ELEMENT b_inicio (#PCDATA)>
<!ELEMENT b_final (#PCDATA)>
<!ELEMENT prestaciones (prestacion)>
<!ELEMENT prestacion (cantidad,p_inicio,p_final)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT p_inicio (#PCDATA)>
<!ELEMENT p_final (#PCDATA)>

=== EmmanuelRamosBiado/Primero-de-Daw/LENGUAJE DE MARCAS/UT6_DTD/Prácticas/Práctica DTD/Ejercicio_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE afiliados SYSTEM "Ejercicio_02.dtd">
<afiliados>
    <afiliado>
        <dni_nie>12345678Z</dni_nie>
        <nombre>Alex</nombre>
        <apellidos>García López</apellidos>
        <situacion situacion="en_paro"></situacion>
        <nacimiento>
            <dia>2</dia>
            <mes>3</mes>
            <anio>1990</anio>
        </nacimiento>
        <bajas>
            <baja>
                <causa>Accidente</causa>
                <b_inicio>2010-2-4</b_inicio>
                <b_final>2010-3-1</b_final>
            </baja>
        </bajas>
        <prestaciones>
            <prestacion>
                <cantidad>1000</cantidad>
                <p_inicio>2010-2-4</p_inicio>
                <p_final>2010-3-1</p_final>
            </prestacion>
        </prestaciones>
    </afiliado>
</afiliados>
